# Quick Intro
This intro will be based on Standford's [CS229: Deep Learning for Natural Language Processing](http://cs224d.stanford.edu/index.html) using numpy.

## Matrix Multiplication
Thing to note: To multiply two matrices, A and B, the number of columns in A must be equal to the number of columns in B. If A has m rows and n columns and B has n rows and p columns, the product of these two matrices will have m rows and p columns. TODO: Add mathematical notations

In [1]:
import numpy as np

#Create two matrices A and B
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

C = A.dot(B)

# Print number of rows and columns of all the matrices
print A.shape, B.shape, C.shape

print C

(2, 3) (3, 4) (2, 4)
[[ 38  44  50  56]
 [ 83  98 113 128]]


## Vectors
A vector is a list (or n-tuples) of numbers. Here are some operations that can be performed on vectors.
### Vector-Vector product
Inner product/dot product
TODO: Mathematical formulation

In [2]:
x = np.array([2, 4, 8])
y = np.array([3, 6, 12])

z1 = x.dot(y)
z2 = np.inner(x, y)
print z1, z2

126 126


Outer vector products:


In [3]:
z3 = np.outer(x, y)
print z3

[[ 6 12 24]
 [12 24 48]
 [24 48 96]]


### Matrix-Vector multiplication

In [4]:
print A.dot(x)

[34 76]


### Properties of matrix multiplication

- Matrix multiplication is associative: (AB)C = A(BC)
- Matrix multiplication is distributive: A(B + C) = AB + AC
- Matrix multiplication, in general, may not be commutative: AB =/= BA if A is [mXn] and B is [nXP]. We cannot multiply BA.

### Identity matrix

Identity matrix is the one where diagonal elements are 1 and all the other elements are 0. It is also a square matrix.

In [5]:
identity = np.eye(3)
print identity

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [8]:
diag_mat = np.zeros((3, 3), int)
np.fill_diagonal(diag_mat, 3)
print diag_mat

[[3 0 0]
 [0 3 0]
 [0 0 3]]


###Transpose of Matrix
Transpose of matrix results from flipping the "rows" and "columns" of a matrix. Following are the properties of matrix transpose:

- (A<sup>T</sup>)<sup>T</sup> = A
- (AB)<sup>T</sup> = B<sup>T</sup>A<sup>T</sup>
- (A + B)<sup>T</sup> = A<sup>T</sup> + B<sup>T</sup>
